### ISSUE TITLE
md-data-table-pagination md-label doesn`t go well with ng-translate

### ISSUE THREAD

**Issue by brunovinicius** [daniel-nagy/md-data-table#195]
I'm using ng-translate to localize my application and cant manage to make md-label work with the translate filter. I think the problem lies in the way two-way bind is used in this parameter to pass both the label and the 'of' string in a object.

I suggest the md-label be split into two parameters and be received by value ('@' instead of '=') so that mustache operator can be applied.

Here's a sample of how I`d expect it to work.

```
 <md-data-table-pagination
    ...
    md-label-text="{{ 'PAGINATION_ROWS_PER_PAGE' | translate }}"
    md-label-of="'{{ 'PAGINATION_OF' | translate }}">
</md-data-table-pagination>
```

Does this proceed, or am I missing something?

**Comment by lucagerotto** [comment]
Hi Bruno, you could use something like that:

<md-data-table-pagination   ...   md-label="pagination.label">
</md-data-table-pagination>

... and define the "pagination" variable in your controller:

angular.module('app').controller('MyController', [ '$scope', '$translate', function( $scope, $translate ){
.... 
$scope.pagination = {
	 label : {
		text : $translate.instant( 'PAGINATION_ROWS_PER_PAGE' ), 
		of   : $translate.instant( 'PAGINATION_OF' )
	  }
 };
...
}]);

**Comment by brunovinicius** [comment]
I did that and it worked! Thanks! Still ita a point of improvement i guess. Thanks for the nice lib anyway =)

**Comment by volmerf** [comment]
I just noticed that I replied to a closed ticket so that's why I place a comment here also. 
Currently there is no 2-way binding currently. Switching the language of the website will not switch the language of the mdLabel. Only on refreshing the page the translation is triggered.

This is our code:

```
vm.updateTranslations();
$rootScope.$on('$translateChangeSuccess', updateTranslations);

function updateTranslations(event) {

            $translate(['GENERAL.PAGINATION.PAGE', 'GENERAL.PAGINATION.ROWS_PER_PAGE', 'GENERAL.PAGINATION.OF']).then(function (translations) {
                vm.paginationLabel.page = translations['GENERAL.PAGINATION.PAGE'];
                vm.paginationLabel.rowsPerPage = translations['GENERAL.PAGINATION.ROWS_PER_PAGE'];
                vm.paginationLabel.of = translations['GENERAL.PAGINATION.OF'];
            });
        }
```

Changing the language will trigger the updateTranslations function but will not update the label.

Could you please fix this in a future release? Thanks.

**Comment by karlhaas** [comment]
I'm having the same issue and I need instant translation whenever the user switches the language.

**Comment by VivienZo** [comment]
+1

**Comment by daniel-nagy** [comment]
@volmerf @karlhaas @VivienZo I just released `v0.10.0` that should allow you to change the label without reloading the page.

**Comment by VivienZo** [comment]
Great! Thank you @daniel-nagy

**Comment by karlhaas** [comment]
Thx @daniel-nagy. Will update and test asap.

**Comment by danielbronder** [comment]
@daniel-nagy Should this issue now be fixed? I have still the same problem. The label will only be changed with reloading the page.
